version: "3"

services:

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka_net

  kafka-1:
    hostname: kafka-1
    container_name: kafka-1
    image: confluentinc/cp-kafka:5.3.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka-logs
    ports:
      - 19092:19092
    depends_on:
      - zookeeper
    networks:
      - kafka_net

  kafka-2:
    hostname: kafka-2
    container_name: kafka-2
    image: confluentinc/cp-kafka:5.3.1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka-logs
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    networks:
      - kafka_net

  kafka-3:
    hostname: kafka-3
    container_name: kafka-3
    image: confluentinc/cp-kafka:5.3.1
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,EXTERNAL://localhost:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka-logs
    ports:
      - 39092:39092
    depends_on:
      - zookeeper
    networks:
      - kafka_net

networks:
  kafka_net:
    name: kafka_net
    external: true

